config/routes.rb
Rails.application.routes.draw do
  resources :members
  resources :attendances
  resources :finances
  resources :events
  resources :members
  resources :permissions
  resources :events
  resources :organizations
  resources :members
  resources :members
  root 'pages#home'

  resources :members do
    member do
      get :delete
    end
  end
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html

  get 'auth/:provider/callback', to: 'sessions#google_auth'
  get 'auth/failure', to: redirect('/')

  #get sign_in_page => 'events#sign_in_page', :as => 'events_sign_in'
end

app/models/finance.rb
class Finance < ApplicationRecord
     validates :member, presence: true
     validates :amount, presence: true
     belongs_to :member

     # This is meant to allow for members to be deleted, but keep the financial records of them
     def self.show_member(finance)
          if Member.where(id: finance.member_id).last.nil?
               'No current member associated'
          else
               Member.where(id: finance.member_id).last.name
          end
     end

     # GET a sum of all the money in the finances table
     def self.sum_finance
          Finance.sum(:amount)
     end
end

app/controllers/finances_controller.rb
class FinancesController < ApplicationController
     before_action :set_finance, only: %i[show edit update destroy]

     # GET /finances or /finances.json
     def index
          @current_member ||= Member.find_by_token(cookies[:token]) if cookies[:token]
          # checking the access type of the current member. If it is 1 and not 0 then show finances page
          if @current_member && @current_member.access_type == 1
               @finances = Finance.all
          else
               redirect_to(root_path) # takes us back the the landing page
          end
     end

     # GET /finances/1 or /finances/1.json
     def show; end

     # GET /finances/new
     def new
          @finance = Finance.new
     end

     # GET /finances/1/edit
     def edit; end

     # POST /finances or /finances.json
     def create
          @finance = Finance.new(finance_params)

          respond_to do |format|
               if @finance.save
                    format.html do
                         redirect_to(@finance, notice: 'Finance was successfully created.')
                    end
                    format.json { render(:show, status: :created, location: @finance) }
               else
                    format.html { render(:new, status: :unprocessable_entity) }
                    format.json { render(json: @finance.errors, status: :unprocessable_entity) }
               end
          end
     end

     # PATCH/PUT /finances/1 or /finances/1.json
     def update
          respond_to do |format|
               if @finance.update(finance_params)
                    format.html do
                         redirect_to(@finance, notice: 'Finance was successfully updated.')
                    end
                    format.json { render(:show, status: :ok, location: @finance) }
               else
                    format.html { render(:edit, status: :unprocessable_entity) }
                    format.json { render(json: @finance.errors, status: :unprocessable_entity) }
               end
          end
     end

     # DELETE /finances/1 or /finances/1.json
     def destroy
          @finance.destroy
          respond_to do |format|
               format.html do
                    redirect_to(finances_url, notice: 'Finance was successfully destroyed.')
               end
               format.json { head(:no_content) }
          end
     end

     private

     # Use callbacks to share common setup or constraints between actions.
     def set_finance
          @finance = Finance.find(params[:id])
     end

     # Only allow a list of trusted parameters through.
     def finance_params
          params.require(:finance).permit(:member_id, :amount)
     end
end

app/helpers/finances_helper.rb
module FinancesHelper
end

app/views/finances/_form.html.erb
<%= form_with(model: finance) do |form| %>
  <% if finance.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(finance.errors.count, "error") %> prohibited this finance from being saved:</h2>

      <ul>
        <% finance.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :member_id %>
    <%= form.select :member_id, Member.order(:name).map { |member| [member.name, member.id] }, include_blank: true, id: "id_of_the_member_id_select_box" %>
  </div>

  <div class="field">
    <%= form.label :amount %>
    <%= form.text_field :amount %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/finances/edit.html.erb
<h1>Editing Finance</h1>

<%= render 'form', finance: @finance %>

<%= link_to 'Show', @finance %> |
<%= link_to 'Back', finances_path %>

app/views/finances/index.html.erb
<p id="notice"><%= notice %></p>

<%@current_member ||= Member.find_by_token(cookies[:token]) if cookies[:token]%>

<% if @current_member && @current_member.access_type == 1 %> 
  <button> <%# Creates a button%>
  <b>
    <%= link_to 'Members', members_path %> <%# Create a new member button %>
  </b>
  </button>
<%else%>
  <button> <%# Creates a button%>
  <b>
    <%= link_to 'My Profile', members_path %> <%# Create a new member button %>
  </b>
  </button>
<%end%>

<button> <%# Creates a button%>
<b>
  <%= link_to 'Events', events_path %> <%# Create a new member button %>
</b>
</button>

<% if @current_member && @current_member.access_type == 1 %> 
  <button> <%# Creates a button%>
  <b>
    <%= link_to 'Attendances', attendances_path %> <%# Create a new member button %>
  </b>
  </button>
<%end%>

<h1>Finances</h1>

<table class="table table-striped">
  <thead>
    <tr>
      <th scope="col">Member</th>
      <th scope="col">Amount</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @finances.each do |finance| %>
      <tr>
        <th scope="row"><%= Finance.show_member(finance) %></td>
        <td><%= finance.amount %></td>
        <td><%= link_to 'Show', finance %></td>
        <td><%= link_to 'Edit', edit_finance_path(finance) %></td>
        <td><%= link_to 'Destroy', finance, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<tbody>
  <tr>
    <td>Total amount of money: </td>
    <td><%= Finance.sum_finance %></td>
  </tr>
</tbody>

<br>
<br>

<%= link_to 'New Finance', new_finance_path %>
<br>
<br>
<%= link_to 'Back to Home', root_path %>

app/views/finances/new.html.erb
<h1>New Finance</h1>

<%= render 'form', finance: @finance %>

<%= link_to 'Back', finances_path %>

app/views/finances/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Member:</strong>
  <%= Finance.show_member(@finance) %>
</p>

<p>
  <strong>Amount:</strong>
  <%= @finance.amount %>
</p>

<%= link_to 'Edit', edit_finance_path(@finance) %> |
<%= link_to 'Back', finances_path %>