config/routes.rb
Rails.application.routes.draw do
  resources :members
  resources :attendances
  resources :finances
  resources :events
  resources :members
  resources :permissions
  resources :events
  resources :organizations
  resources :members
  resources :members
  root 'pages#home'

  resources :members do
    member do
      get :delete
    end
  end
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html

  get 'auth/:provider/callback', to: 'sessions#google_auth'
  get 'auth/failure', to: redirect('/')

  #get sign_in_page => 'events#sign_in_page', :as => 'events_sign_in'
end

app/models/event.rb
class Event < ApplicationRecord
     validates :name, presence: true
     validates :date, presence: true
     validates :location, presence: true
     has_one :attendance, :dependent => :destroy

     def self.sign_in_page(current_member, current_event)
          # Compare date time, give a 60 minute period in which members can sign in
          # 1800 for 30 minutes to sign in before or after the event starts
          # 21600 for 6 hour offset that comes with utc time zone
          @time1 = DateTime.now.utc > current_event.date + 19_800
          @time2 = DateTime.now.utc < current_event.date + 23_400
          if current_member && @time1 && @time2
               Attendance.create_attendance(current_member, current_event)
               0
          elsif current_member
               1
          end
     end
end

app/controllers/events_controller.rb
class EventsController < ApplicationController
     before_action :set_event, only: %i[show edit update destroy]

     # GET /events or /events.json
     def index
          @current_member ||= Member.find_by_token(cookies[:token]) if cookies[:token]
          @events = Event.all
     end

     # GET /events/1 or /events/1.json
     def show
          @current_member ||= Member.find_by_token(cookies[:token]) if cookies[:token]
          @current_event = Event.find(params[:id])
          @val = Event.sign_in_page(@current_member, @current_event)
          if @val != 1
               flash[:notice] = 'Member has received points for the event.'
          elsif @val == 1
               flash[:notice] = 'Event 60 minute sign in window is over.'
          else
               flash[:notice] = 'Member is not signed in, please sign in to receive points.'
               redirect_to('/auth/google_oauth2')
          end
     end

     # GET /events/new
     def new
          @event = Event.new
     end

     # GET /events/1/edit
     def edit; end

     # POST /events or /events.json
     def create
          @event = Event.new(event_params)

          respond_to do |format|
               if @event.save
                    # message that returns if event was successfully created
                    format.html do
                         redirect_to(@event, notice: 'Event was successfully created.')
                    end
                    format.json { render(:show, status: :created, location: @event) }
               else
                    format.html { render(:new, status: :unprocessable_entity) }
                    format.json { render(json: @event.errors, status: :unprocessable_entity) }
               end
          end
     end

     # PATCH/PUT /events/1 or /events/1.json
     def update
          respond_to do |format|
               if @event.update(event_params)
                    # message that returns if event was successfully updated
                    format.html do
                         redirect_to(@event, notice: 'Event was successfully updated.')
                    end
                    format.json { render(:show, status: :ok, location: @event) }
               else
                    format.html { render(:edit, status: :unprocessable_entity) }
                    format.json { render(json: @event.errors, status: :unprocessable_entity) }
               end
          end
     end

     # DELETE /events/1 or /events/1.json
     def destroy
          @event.destroy
          respond_to do |format|
               # message that returns if event was successfully destroyed
               format.html do
                    redirect_to(events_url, notice: 'Event was successfully destroyed.')
               end
               format.json { head(:no_content) }
          end
     end

     private

     # Use callbacks to share common setup or constraints between actions.
     def set_event
          @event = Event.find(params[:id])
     end

     # Only allow a list of trusted parameters through.
     def event_params
          params.require(:event).permit(:date, :location, :name)
     end
end

app/helpers/events_helper.rb
module EventsHelper
end

app/views/events/_form.html.erb
<%= form_with(model: event) do |form| %>
  <% if event.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(event.errors.count, "error") %> prohibited this event from being saved:</h2>

      <ul>
        <% event.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :name %>
    <%= form.text_field :name %>
  </div>

  <div class="field">
    <%= form.label :date %>
    <%= form.datetime_local_field :date %>
  </div>

  <div class="field">
    <%= form.label :location %>
    <%= form.text_field :location %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/events/edit.html.erb
<h1>Editing Event</h1>

<%= render 'form', event: @event %>

<%= link_to 'Show', @event %> |
<%= link_to 'Back', events_path %>

app/views/events/index.html.erb
<p id="notice"><%= notice %></p>

<%@current_member ||= Member.find_by_token(cookies[:token]) if cookies[:token]%>

<% if @current_member && @current_member.access_type == 1 %> 
  <button> <%# Creates a button%>
  <b>
    <%= link_to 'Members', members_path %> <%# Create a new member button %>
  </b>
  </button>
<%else%>
  <button> <%# Creates a button%>
  <b>
    <%= link_to 'My Profile', members_path %> <%# Create a new member button %>
  </b>
  </button>
<%end%>

<% if @current_member && @current_member.access_type == 1 %> 
  <button> <%# Creates a button%>
  <b>
    <%= link_to 'Finances', finances_path %> <%# Create a new member button %>
  </b>
  </button>
<%end%>

<% if @current_member && @current_member.access_type == 1 %> 
  <button> <%# Creates a button%>
  <b>
    <%= link_to 'Attendances', attendances_path %> <%# Create a new member button %>
  </b>
  </button>
<%end%>

<h1>Events</h1>

<%@current_member ||= Member.find_by_token(cookies[:token]) if cookies[:token] %>

<table class="table table-striped">
  <thead>
    <tr>
      <%# table column titles %>
      <th scope="col">Name</th>
      <th scope="col">Date</th>
      <th scope="col">Location</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @events.each do |event| %>
      <tr>
        <td><%= event.name %></td>
        <%# For each of the members show their date and location and give the option to show edit or destroy %>
        <th scope="row"><%= event.date.strftime("%Y-%m-%d %l:%m%P ") %></td>
        <td><%= event.location %></td>
        <td><%= link_to 'Get Points', event%></td>
        <% if @current_member && @current_member.access_type == 1 %>
          <td><%= link_to 'Edit', edit_event_path(event) %></td>
          <td><%= link_to 'Destroy', event, method: :delete, data: { confirm: 'Are you sure?' } %></td>
        <% end %>
      </tr>
    <% end %>
  </tbody>
</table>

<br>


<% if @current_member && @current_member.access_type == 1 %>
  <%= link_to 'New Event', new_event_path %>
<% end %>
<br>
<br>
<%= link_to 'Back to Home', root_path %>

app/views/events/new.html.erb
<h1>New Event</h1>

<%= render 'form', event: @event %>

<%= link_to 'Back', events_path %>

app/views/events/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @event.name %>
</p>

<p>
  <strong>Date:</strong>
  <%= @event.date %>
</p>

<p>
  <strong>Location:</strong>
  <%= @event.location %>
</p>

<%@current_member ||= Member.find_by_token(cookies[:token]) if cookies[:token]%>
<% if @current_member && @current_member.access_type == 1 %> 
  <%= link_to 'Edit', edit_event_path(@event) %> |
<%else%>
<%#! Else should be empty be default %>
<%end%>

<%= link_to 'Back', events_path %>