config/routes.rb
Rails.application.routes.draw do
  resources :members
  resources :attendances
  resources :finances
  resources :events
  resources :members
  resources :permissions
  resources :events
  resources :organizations
  resources :members
  resources :members
  root 'pages#home'

  resources :members do
    member do
      get :delete
    end
  end
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html

  get 'auth/:provider/callback', to: 'sessions#google_auth'
  get 'auth/failure', to: redirect('/')

  #get sign_in_page => 'events#sign_in_page', :as => 'events_sign_in'
end

app/models/attendance.rb
class Attendance < ApplicationRecord
     validates :member, presence: true
     validates :event, presence: true
     belongs_to :member
     belongs_to :event

     def self.create_attendance(current_member, current_event)
          if Attendance.where(member: current_member, event: current_event).last.nil?
               @attendance = Attendance.new({ member: current_member, event: current_event })
               @attendance.save
          end
     end
end

app/controllers/attendances_controller.rb
class AttendancesController < ApplicationController
     before_action :setAttendance, only: %i[show edit update destroy]

     # GET /attendances or /attendances.json
     def index
          @current_member ||= Member.find_by_token(cookies[:token]) if cookies[:token]

          # checking the access type of the current member. If it is 1 and not 0 then show attendances page
          if @current_member && @current_member.access_type == 1
               @attendances = Attendance.all
          else
               redirect_to(root_path) # takes us back the the landing page
          end
     end

     # GET /attendances/1 or /attendances/1.json
     def show; end

     # GET /attendances/new
     def new
          @attendance = Attendance.new
     end

     # GET /attendances/1/edit
     def edit; end

     # POST /attendances or /attendances.json
     def create
          @attendance = Attendance.new(attendanceParams)

          respond_to do |format|
               if @attendance.save
                    format.html do
                         redirect_to(@attendance, notice: 'Attendance was successfully created.')
                    end
                    format.json { render(:show, status: :created, location: @attendance) }
               else
                    format.html { render(:new, status: :unprocessable_entity) }
                    format.json { render(json: @attendance.errors, status: :unprocessable_entity) }
               end
          end
     end

     # PATCH/PUT /attendances/1 or /attendances/1.json
     def update
          respond_to do |format|
               if @attendance.update(attendanceParams)
                    format.html do
                         redirect_to(@attendance, notice: 'Attendance was successfully updated.')
                    end
                    format.json { render(:show, status: :ok, location: @attendance) }
               else
                    format.html { render(:edit, status: :unprocessable_entity) }
                    format.json { render(json: @attendance.errors, status: :unprocessable_entity) }
               end
          end
     end

     # DELETE /attendances/1 or /attendances/1.json
     def destroy
          @attendance.destroy
          respond_to do |format|
               format.html do
                    redirect_to(attendances_url, notice: 'Attendance was successfully destroyed.')
               end
               format.json { head(:no_content) }
          end
     end

     private

     # Use callbacks to share common setup or constraints between actions.
     def setAttendance
          @attendance = Attendance.find(params[:id])
     end

     # Only allow a list of trusted parameters through.
     def attendanceParams
          params.require(:attendance).permit(:member_id, :event_id)
     end
end

app/helpers/attendances_helper.rb
module AttendancesHelper
end

app/views/attendances/_form.html.erb
<%= form_with(model: attendance) do |form| %>
  <% if attendance.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(attendance.errors.count, "error") %> prohibited this attendance from being saved:</h2>

      <ul>
        <% attendance.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :member_id %>
    <%= form.select :member_id, Member.order(:name).map { |member| [member.name, member.id] }, include_blank: true, id: "id_of_the_member_id_select_box" %>

  </div>

  <div class="field">
    <%= form.label :event_id %>
    <%= form.select :event_id, Event.order(:location).map { |event| [event.location, event.id] }, include_blank: true, id: "id_of_the_event_id_select_box" %>

  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/attendances/edit.html.erb
<h1>Editing Attendance</h1>

<%= render 'form', attendance: @attendance %>

<%= link_to 'Show', @attendance %> |
<%= link_to 'Back', attendances_path %>

app/views/attendances/index.html.erb
<p id="notice"><%= notice %></p>

<%@current_member ||= Member.find_by_token(cookies[:token]) if cookies[:token]%>

<% if @current_member && @current_member.access_type == 1 %> 
  <button> <%# Creates a button%>
  <b>
    <%= link_to 'Members', members_path %> <%# Create a new member button %>
  </b>
  </button>
<%else%>
  <button> <%# Creates a button%>
  <b>
    <%= link_to 'My Profile', members_path %> <%# Create a new member button %>
  </b>
  </button>
<%end%>

<button> <%# Creates a button%>
<b>
  <%= link_to 'Events', events_path %> <%# Create a new member button %>
</b>
</button>

<% if @current_member && @current_member.access_type == 1 %> 
  <button> <%# Creates a button%>
  <b>
    <%= link_to 'Finances', finances_path %> <%# Create a new member button %>
  </b>
  </button>
<%end%>

<h1>Attendances</h1>

<table class="table table-striped">
  <thead>
    <tr>
      <th scope="col">Member</th>
      <th scope="col">Event</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @attendances.each do |attendance| %>
      <tr>
        <th scope="row">><%= Member.where(id: attendance.member_id).last.name %></td>
        <td><%= Event.where(id: attendance.event_id).last.name %></td>
        <td><%= link_to 'Show', attendance %></td>
        <td><%= link_to 'Edit', edit_attendance_path(attendance) %></td>
        <td><%= link_to 'Destroy', attendance, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Attendance', new_attendance_path %>

<br>
<br>
<%= link_to 'Back to Home', root_path %>

app/views/attendances/new.html.erb
<h1>New Attendance</h1>

<%= render 'form', attendance: @attendance %>

<%= link_to 'Back', attendances_path %>

app/views/attendances/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Member:</strong>
  <%= @attendance.member_id %>
</p>

<p>
  <strong>Event:</strong>
  <%= @attendance.event_id %>
</p>

<%= link_to 'Edit', edit_attendance_path(@attendance) %> |
<%= link_to 'Back', attendances_path %>