config/routes.rb
Rails.application.routes.draw do
  resources :members
  resources :attendances
  resources :finances
  resources :events
  resources :members
  resources :permissions
  resources :events
  resources :organizations
  resources :members
  resources :members
  root 'pages#home'

  resources :members do
    member do
      get :delete
    end
  end
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html

  get 'auth/:provider/callback', to: 'sessions#google_auth'
  get 'auth/failure', to: redirect('/')

  #get sign_in_page => 'events#sign_in_page', :as => 'events_sign_in'
end

app/models/member.rb
class Member < ApplicationRecord
     validates :name, presence: true
     validates :email, presence: true
     validates :access_type, presence: true
     validates :paid_status, presence: true
     validates :points, presence: true

     validates :name, presence: true
     validates :email, presence: true
     validates :access_type, presence: true
     validates :paid_status, presence: true
     validates :points, presence: true

     has_one :finance
     has_many :attendances

     # attr_reader :access_type, :paid_status

     # https://stackoverflow.com/questions/10863084/omniauth-how-to-keep-user-logged-in-after-browser-is-closed
     before_save :generate_token
     def generate_token
          self.token = SecureRandom.urlsafe_base64
     end

     # https://medium.com/@amoschoo/google-oauth-for-ruby-on-rails-129ce7196f35
     def self.from_omniauth(auth)
          member = Member.find_by(email: auth.info.email)
          if member.nil?
               # Creates a new user only if it doesn't exist
               where(email: auth.info.email).first_or_initialize do |member|
                    member.name = auth.info.name
                    member.email = auth.info.email
                    member.points = 0
                    member.paid_status = 0
                    #! This is changed to 1 for testing purposes, needs to be changed back later
                    member.access_type = 0
                    member.save
                    return member
               end
          end
          member
     end
end

app/controllers/members/omniauth_callbacks_controller.rb
class Members::OmniauthCallbacksController < Devise::OmniauthCallbacksController
    def google_oauth2
        # You need to implement the method below in your model (e.g. app/models/user.rb)
        @member = Member.from_omniauth(request.env['omniauth.auth'])
  
        if @member.persisted?
          flash[:notice] = I18n.t 'devise.omniauth_callbacks.success', kind: 'Google'
          sign_in_and_redirect @member, event: :authentication
        else
          session['devise.google_data'] = request.env['omniauth.auth'].except('extra') # Removing extra as it can overflow some session stores
          redirect_to new_member_registration_url, alert: @member.errors.full_messages.join("\n")
        end
    end
  end

app/controllers/members_controller.rb
class MembersController < ApplicationController
     before_action :set_member, only: %i[show edit update destroy]

     # GET /members or /members.json (going to to members table)
     def index
          @current_member ||= Member.find_by_token(cookies[:token]) if cookies[:token]
          if @current_member && @current_member.access_type == 1
               @members = Member.all
          elsif @current_member.nil?
               redirect_to('/auth/google_oauth2')
          else
               # redirect_to member_url(Member.find_one(@current_member.id))

               # iterate through memmbers until we find a matching token
               # if match then redirect to that member
               # indexOfTokenMatch = 0
               # for i in 1..Member.count do
               #      # puts "--------Member Token from array: " + Member.find(i).token
               #      # puts "--------Member Token from current member: " + cookies[:token]

               #      indexOfTokenMatch = i if Member.find(i).token == cookies[:token]
               # end

               if Member.count <= 0
                    redirect_to('/auth/google_oauth2')
               end
               
               @current_member ||= Member.find_by_token(cookies[:token]) if cookies[:token]
               
               if @current_member == nil
                    redirect_to('/auth/google_oauth2')
               else
                    redirect_to(action: 'show', id: @current_member.id)
               end
          end
     end

     # GET /members/1 or /members/1.json
     def show; end

     # GET /members/new
     def new
          @member = Member.new
     end

     # GET /members/1/edit
     def edit; end

     # POST /members or /members.json
     def create
          @member = Member.new(member_params)

          respond_to do |format|
               if @member.save
                    format.html { redirect_to(@member, notice: 'Member was successfully created.') }
                    format.json { render(:show, status: :created, location: @member) }
               else
                    format.html { render(:new, status: :unprocessable_entity) }
                    format.json { render(json: @member.errors, status: :unprocessable_entity) }
               end
          end
     end

     # PATCH/PUT /members/1 or /members/1.json
     def update
          respond_to do |format|
               if @member.update(member_params)
                    format.html { redirect_to(@member, notice: 'Member was successfully updated.') }
                    format.json { render(:show, status: :ok, location: @member) }
               else
                    format.html { render(:edit, status: :unprocessable_entity) }
                    format.json { render(json: @member.errors, status: :unprocessable_entity) }
               end
          end
     end

     # DELETE /members/1 or /members/1.json
     def destroy
          @member.destroy
          respond_to do |format|
               format.html do
                    redirect_to(members_url, notice: 'Member was successfully destroyed.')
               end
               format.json { head(:no_content) }
          end
     end

     private

     # Use callbacks to share common setup or constraints between actions.
     def set_member
          @member = Member.find(params[:id])
     end

     # Only allow a list of trusted parameters through.
     def member_params
          params.require(:member).permit(:name, :email, :token, :access_type, :paid_status, :points)
     end
end

app/helpers/members_helper.rb
module MembersHelper
end

app/views/members/_form.html.erb
<%= form_with(model: member) do |form| %>
  <% if member.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(member.errors.count, "error") %> prohibited this member from being saved:</h2>

      <ul>
        <% member.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <%# Only Officers can change %>
  <div class="field">
    <%= form.label :name %>
    <%= form.text_field :name %>
  </div>

  <%# Only Officers can change %>
  <div class="field">
    <%= form.label :email %>
    <%= form.text_field :email %>
  </div>

  <%# Only Officers can change %>
  <div class="field">
    <%= form.label :token %>
    <%= form.text_field :token %>
  </div>

  <%# Only Officers can change %>
    <div class="field">
      <%= form.label :access_type %>
      <%= form.number_field :access_type %>
    </div>

    <%# Only Officers can change %>
    <div class="field">
      <%= form.label :paid_status %>
      <%= form.number_field :paid_status %>
    </div>

    <%# Only Officers can change %>
    <div class="field">
      <%= form.label :points %>
      <%= form.number_field :points %>
    </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/members/edit.html.erb
<h1>Editing Member</h1>

<%= render 'form', member: @member %>

<%= link_to 'Show', @member %> |
<%= link_to 'Back', members_path %>

app/views/members/index.html.erb
<p id="notice"><%= notice %></p>

<%@current_member ||= Member.find_by_token(cookies[:token]) if cookies[:token]%>


<button> <%# Creates a button%>
<b>
  <%= link_to 'Events', events_path %> <%# Create a new member button %>
</b>
</button>

<% if @current_member && @current_member.access_type == 1 %> 
  <button> <%# Creates a button%>
  <b>
    <%= link_to 'Finances', finances_path %> <%# Create a new member button %>
  </b>
  </button>
<%end%>

<% if @current_member && @current_member.access_type == 1 %> 
  <button> <%# Creates a button%>
  <b>
    <%= link_to 'Attendances', attendances_path %> <%# Create a new member button %>
  </b>
  </button>
<%end%>



<h1>Members</h1>

<table class="table table-striped">
  <thead>
    <tr>
      <%# Table column titles %>
      <th scope="col">Name</th>
      <th scope="col">Email</th>
      <th scope="col">Access type</th>
      <th scope="col">Paid status</th>
      <th scope="col">Points</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <%# for each of the members how their name, email, token, access type, paid status, and points and give the option to show edit or destroy %>
    <% @members.each do |member| %>
      <tr>
        <th scope="row"><%= member.name %></td>
        <td><%= member.email %></td>
        <td><%= member.access_type %></td>
        <td><%= member.paid_status %></td>
        <td><%= member.points %></td>
        
        <td><%= link_to 'Show', member %></td>
        <td><%= link_to 'Edit', edit_member_path(member) %></td>
        <td><%= link_to 'Destroy', member, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'Create a New Member', new_member_path %> <%# Create a new member button %>
<br>
<br>
<%= link_to 'Back to Home', root_path %>

app/views/members/new.html.erb
<h1>New Member</h1>

<%= render 'form', member: @member %>

<%= link_to 'Back', members_path %>

app/views/members/show.html.erb
<p id="notice"><%= notice %></p>

<%@current_member ||= Member.find_by_token(cookies[:token]) if cookies[:token]%>

<button> <%# Creates a button%>
<b>
  <%= link_to 'Events', events_path %> <%# Create a new member button %>
</b>
</button>

<% if @current_member && @current_member.access_type == 1 %> 
  <button> <%# Creates a button%>
  <b>
    <%= link_to 'Finances', finances_path %> <%# Create a new member button %>
  </b>
  </button>
<%end%>

<% if @current_member && @current_member.access_type == 1 %> 
  <button> <%# Creates a button%>
  <b>
    <%= link_to 'Attendances', attendances_path %> <%# Create a new member button %>
  </b>
  </button>
<%end%>

<br>
<br>

<h1>My Info</h1>

<table class="table table-striped">
  <thead>
    <tr>
      <th scope="col">Name</th>
      <th scope="col">Email</th>
      <th scope="col">Access type</th>
      <th scope="col">Paid status</th>
      <th scope="col">Points</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <tr>
      <th scope="row"><%= @member.name %></td>
      <td><%= @member.email %></td>
      <td><%= @member.access_type %></td>
      <td><%= @member.paid_status %></td>
      <td><%= @member.points %></td>
    </tr>
  </tbody>
</table>

<%@current_member ||= Member.find_by_token(cookies[:token]) if cookies[:token]%>

<% if @current_member && @current_member.access_type == 1 %> <%#! Change to 0 if needed%>
  <%= link_to 'Edit', edit_member_path(@member) %> |
<%end%>

<% if @current_member && @current_member.access_type == 1 %> 
  <%= link_to 'Back', members_path %>
<%else%>
  <%= link_to 'Back', root_path %>
<%end%>